### PR TITLE
Add Fusion connected textures for the pressure_chamber_glass texture

### PR DESCRIPTION
**Pull request by Reabstraction**
This pull requests adds Fusion connected textures to the pressure_chamber_glass texture

Its an optional resource pack that is ONLY enabled if Fusion is detected
If it isn't, we never show the resource pack to the user

### CODE REVIEW

**Comment by Reabstraction** [comment]
I added streaks the glass to prevent a situation where you can't see the glass properly when you have a giant wall of glass

I have no problem with removing it if requested by the maintainers

**Comment by desht** [comment]
This looks good, thanks. Will take a closer look this week hopefully (sorry been real busy IRL lately)

**Comment by desht** [comment]
Hi, sorry for the delay. The change is good, but I would prefer the third party mod detection is all kept within `ThirdPartyManager`. Proposed changes:

* Add a constant for `FUSION` in `ModIds`
* Create a `me.desht.pneumaticcraft.common.thirdparty.Fusion` class which implements `IThirdParty`
* Override `clientPreInit()` (which is called at mod construction) to register the `AddPackFindersEvent`, and put the event listener in that class (I'm pretty sure this is only needed client side? If it's needed on both sides, override `preInit()` instead)
* Update `ThirdPartyManager#discoverMods` to register the class you created

I appreciate it's a bit more work, but I like to keep all references to other mods within the third-party system.

**Comment by Reabstraction** [comment]
@desht I have updated it to use IThirdParty
+ Fixed the "Install CTM" popup to reference Fusion and also disappear if Fusion is installed
+ Migrate code to IThirdParty

**Comment by desht** [comment]
Merged, thanks!

**Comment by desht** [comment]
So maybe I should have tested before merging :smile:  It's not actually working for me.  Still seeing unconnected pressure glass textures with this merged in and the Fusion mod (1.1.1a) in my instance.

Update: oh, never mind. Just needed to actually enable the Fusion for PneumaticCraft resource pack in my client. Looks good now!

**Comment by Reabstraction** [comment]
> So maybe I should have tested before merging 😄 It's not actually working for me. Still seeing unconnected pressure glass textures with this merged in and the Fusion mod (1.1.1a) in my instance.
> 
> Update: oh, never mind. Just needed to actually enable the Fusion for PneumaticCraft resource pack in my client. Looks good now!

As I usually do when making integrations, it's optional.
Not everyone likes having random texture changes without an obvious cause.
Plus not everyone may like the connected textures

**Pull request merged**
