### PR TITLE
Add Torus area type

### PR DESCRIPTION
**Pull request by johalun**
This change adds the Torus area type. P1 is assumed to be in the center of the torus. When radially symmetric about the Y-axis, the distance between P1 and P2 in the X/Z plane makes the radius of the torus to the center of the tube and the distance in Y makes the radius of the tube.

Algorithm and variable naming from
https://en.wikipedia.org/wiki/Torus

### CODE REVIEW

**Comment by desht** [comment]
Merged, thanks!

**Comment by johalun** [comment]
Awesome, thanks for the merge! When do you think we'll see the next release?

**Comment by desht** [comment]
Planning for a 1.20 release in the next day or two (I cherry picked the commit into 1.20 too)

1.19 maybe this week too?

**Comment by johalun** [comment]
> 1.19 maybe this week too?

Sounds good! Looking forward to getting this and the round robin improvements on our server.

**Comment by desht** [comment]
4.3.9 for 1.19.2 is up on CF & Modrinth now (as is 6.0.9 for 1.20.1)

**Comment by johalun** [comment]
Awesome, thank you!!

**Pull request merged**
