### PR TITLE
Redstone tube module overhaul

### PR DESCRIPTION
**Pull request by shBLOCK**
This PR brings quite a lot of improvements to the redstone tube module system.

Why
-----
I was working on automating the endergenic generators from RFTools and discovered that the timings of redstone modules were inconsistent.

Improvements
-----
- Performance: outputting redstone modules only recalculate and update when input levels of its channel (or its "other channel" (for advanced config operations)) change. They were updating every tick.
- Performance: the inputting levels of a network are calculated only once for each input update, instead of for every output module on each tick. I didn't cache the input levels for simplicity and compatibility reasons.
- Consistency: the timings of redstone modules are now consistent. Down below is a simple demo of the consistency problem. Here the two lines are the same configuration (a chain of input-output modules), except that I placed one of them from left to right and the other one from right to left, which affects the tick order of the tubes.
java_2cvlgwkZz4
This is how it works with my patch:
java_NbcX2X7Nzy
- Fix: this (probably) unintentional behavior:

https://github.com/TeamPneumatic/pnc-repressurized/assets/50770712/0a8b2b74-818d-482b-b66e-04184336a13f

  This "diode" effect is "inverted" as a result of the changes in updating logic, which becomes quite strange, so I got rid of it.
- Cleanup: introduced `AbstractNetworkedRedstoneModule` to unify the redstone module network logic. `RedstoneModule` and `ThermostatModule` now inherits `AbstractNetworkedRedstoneModule`. This would also make future features related to redstone modules easier (for example, the proposal to make logistics modules to respond to redstone module inputs).

Compatibility
-----
- For world loading/saving:
  - Redstone module: both forward and backward compatibility are maintained, as I didn't alter any usages of the nbt tags
  - Thermostat module: ~only forward compatibility is maintained, as the `level` tag was removed~ testing shows that both forward and backward compatibility **is** maintained even though the `level` tag was removed.
- Redstone logic
  - These changes shouldn't affect most builds, except if they depend on the inconsistent behaviors to work properly, this is very unlikely though, as exact timing is not critical for most builds. Also, they would probably prefer this change if the build is actually timing-critical. 
  - Loop updates are handled properly and should work mostly the same as before (here in the clip the output is inverted and feeds back to the input so it becomes an update loop):
java_Ws7LtwZw6t
  - I've built this out and tested it on my endergenic automation and it works perfectly now.

### CODE REVIEW

**Comment by shBLOCK** [comment]
Hmm, I figured out why the output modules aren't updating sometimes, there seem to be strange things going on with `ModuleNetworkManager`.
`ModuleNetworkManager.getConnectedModules()` is called on both client side and server side, so in single player the cache gets client-side instances of tube modules sometimes. I think this is unintentional but it's worth mentioning. I'm gonna add a check in `getConnectedModules` just to be safe.

**Comment by shBLOCK** [comment]
There's one more problem. The input signal level often desyncs on the client side (shows "Receiving redstone: -1" via jade, and lights up even though it's not receiving anything). This doesn't happen for output levels since they are saved to the nbt and thus is automatically synced.
Currently, `saveAdditional()` automatically calls `writeToPacket()` in `AbstractPneumaticCraftBlockEntity`. I think it'd be a good idea to separate them out so that we can send different information for syncing for saving.
I'm not sure if this change is acceptable so I'm asking here.

**Comment by shBLOCK** [comment]
Validated on a dedicated server with my endergenic setup, and they run at maximum efficiency now :)
<details><summary>Details</summary>
<p>

image

</p>
</details>

**Comment by desht** [comment]
From an initial look, this looks pretty good, thanks!

I'll load this up in a dev instance and do some testing and take a more detailed look at your changes hopefully in the next few days.

**Comment by shBLOCK** [comment]
> There's one more problem. The input signal level often desyncs on the client side (shows "Receiving redstone: -1" via jade, and lights up even though it's not receiving anything). This doesn't happen for output levels since they are saved to the nbt and thus is automatically synced. Currently, `saveAdditional()` automatically calls `writeToPacket()` in `AbstractPneumaticCraftBlockEntity`. I think it'd be a good idea to separate them out so that we can send different information for syncing for saving. I'm not sure if this change is acceptable so I'm asking here.

Just as a reminder, I'm waiting for your opinion on this potential refactor to solve the syncing problem more gracefully, since it is going to affect many tileentity implementations.

**Comment by johalun** [comment]
Nice! 👍🏻

**Comment by desht** [comment]
> Just as a reminder, I'm waiting for your opinion on this potential refactor to solve the syncing problem more gracefully, since it is going to affect many tileentity implementations.

It probably would make sense, but that does feel like a much bigger change, beyond the scope of this particular addition. I'll be testing your changes thoroughly this weekend in any case (sorry it's taken so long, I am interested in getting this merged, honest!)

I'll have a think about the client-side input desyncs.

**Comment by desht** [comment]
So I finally got the chance to do some testing, and it mostly works great, but I can see one big problem: redstone modules in clock mode don't tick anymore.  So that needs sorting out...

**Comment by desht** [comment]
Thanks, that change makes clocks work again.  Been doing some more testing, and I'm fairly happy with this. 

Regarding the -1 input level showing up on clients: yes, the current extra-data sync method (`writeToPacket()`) is not... good. It basically sends all this data over the wire encoded as NBT, which is horribly inefficient, and there definitely does need to be a separation of sync'ing and saving. Which means every class which requires `writeToPacket()` for sync'ing must have get new `writeToNetwork` and `readFromNetwork` methods to be called from `PacketDescription`.

That is outside the scope of this PR, though. In the short term, I think I have a change which solves the immediate problem of -1 input levels showing up on the client; at least in all my testing, the problem does appear to have gone away (and not cause any other problems). I can't push directly to your PR brach, so f you wouldn't mind applying the attached patch and doing some testing of your own, that would be great.

**Comment by desht** [comment]
[input-sync-patch.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/14156588/input-sync-patch.txt)

**Comment by shBLOCK** [comment]
Okay, this definitely fixed the client sync problem, but it does seem like I've broken something again.
A output module gets desynced with the network's input levels when you disconnect and then reconnect it to the network.
EDIT: The condition is actually pretty specific, you have to update the block neighboring to the output/input module to trigger this, so it might also be a newly discovered bug.
I'm going to commit your changes first then try to figure that out.
(Btw you should be able to commit to my branch, "Allow edits by maintainers" is on, or is it because of merge conflicts?)

**Comment by desht** [comment]
> Btw you should be able to commit to my branch, "Allow edits by maintainers" is on, or is it because of merge conflicts?)

Yeah, ignore me, I'm an idiot. I cloned your branch via HTTP instead of SSH :blush:

**Comment by shBLOCK** [comment]
Okay, it is fixed, and, upon loading up old test worlds it looks like everything else still works fine.
This should be safe to merge now!

**Comment by desht** [comment]
Yep, I'm happy with this, merging - thanks for the good work here!

**Pull request merged**
