### PR TITLE
Heat Sink now uses Vanilla Freezing effect and damage

### PR DESCRIPTION
**Pull request by Lgmrszd**
Some improvements to Heat Sink:
- Uses Vanilla freezing instead of damaging directly.
- Uses Vanilla damage type at low temperatures.

### CODE REVIEW

**Comment by desht** [comment]
Rather than just deleting `DamageSourcePneumaticCraft.FREEZING`, how about  just making it the same as `DamageSource.FREEZE` for now (and mark it deprecated for removal in 1.19) ?  Avoid an API break that way, just in case someone is using that damage type...

**Comment by Lgmrszd** [comment]
By the way, current behaviour is a bit different now:
With temperature <30 ≥ 60, it acts like if the player/entity is standing in Powdered Snow block, and slowness is not applied, as frozen entities are slowed down anyway. This can be bypassed by wearing piece of leather armor or other armor in corresponding tag.
Below 60 degrees, it forces entity to freeze (with freezing speed amplified by the temperature) and after its frozen, applies additional damage. Feel free to change that if that's not fitting!
Also, probably pneumatic armor and/or compressed iron armor could be added to the vanilla tag to bypass powdered snow, I am not sure what approach would be better.

**Comment by TeamSpen210** [comment]
Compressed Iron armour is just normal, so it shouldn't do anything special. For pneumatic armour it probably should require an upgrade, perhaps the two parts could be split up? Have the air conditioning upgrade on the chestplate to block the freezing damage, and then maybe something else in the boots (stilts? dunno) that handles the movement debuff, maybe also apply to soulsand.

**Comment by desht** [comment]
I presume the thinking here is that Leather Armour blocks vanilla cold, and Compressed (and thus Pneumatic) Armor requires the corresponding leather pieces to make.  Therefore they should also block vanilla cold sources. Which is reasonable; both sets effectively have a leather "lining".

As I understand, the intention is for PNC:R cold to act like vanilla from -30C to -60C, and apply extra debuffs/damage below that @Lgmrszd ?

**Comment by desht** [comment]
Oh, as it stands right now, Pneumatic Boots with the Flippers upgrade prevents sinking in Powder Snow.  I'd leave that as it is, and probably bring back the Air Conditioning upgrade to deal with cold effects (both from PNC and other mods like Cold Sweat).

**Comment by desht** [comment]
To summarise:
* I'll merge this PR today and have a play with it
* Pneumatic Boots will continue to require the Flippers upgrade to prevent sinking
* I will add Compressed & Pneumatic armour piece to `minecraft:freeze_immune_wearables` so they protect against vanilla cold (Powder Snow) damage, as well as heat sinks -30C -> -60C
* PNC:R freeze damage (i.e. from heat sinks < -60C) will continue to hurt the player, but I plan to do something with the Air Conditioning upgrade to mitigate that (along with Cold Sweat and possibly Tough as Nails support)
* (Related) I'll also look at Minigun freeze ammo with a view to better vanilla integration (calling `Entity#setTicksFrozen()`, basically)

**Pull request merged**
